name: For /helloworld
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/helloworld.yaml'
      - 'helloworld/**'
defaults:
  run:
    shell: bash
    working-directory: helloworld
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          ls -la
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
